name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          workload_identity_provider: projects/hackathon-cp-project-team-1/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: hackathon-cp-project-team-1@appspot.gserviceaccount.com
          project_id: hackathon-cp-project-team-1

      - name: Authenticate to Google Cloud
        run: gcloud auth application-default login --no-launch-browser
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Apply
        run: terraform apply -auto-approve


        name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
