name: Deploy Infrastructure

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI    
    env:
      PROJECT_ID: hackathon-cp-project-team-1
      REGION: us-central1
      PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
      PRIVATE_KEY_ID: ${{ secrets.PRIVATEKEYID }}
      CLIENT_ID: ${{ secrets.CLIENTID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/1054015443281/locations/global/workloadIdentityPools/gemini-rag/subject/SUBJECT_ATTRIBUTE_VALUE'
          service_account: 'hackathon-cp-project-team-1@appspot.gserviceaccount.com'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Display service account key file (for debugging, remove this in production)
        run: cat $HOME/gcp-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Set GCP project
        run: gcloud config set project hackathon-cp-project-team-1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -var="project_id=hackathon-cp-project-team-1" -var="region=us-central1" -auto-approve
