name: Terraform on GCP

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          workload_identity_provider: projects/hackathon-cp-project-team-1/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: hackathon-cp-project-team-1@appspot.gserviceaccount.com
          project_id: hackathon-cp-project-team-1

      - name: Configure Google Cloud SDK
        run: |
          gcloud config set project ${{ steps.auth.outputs.project_id }}

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Apply
        run: |
          terraform apply -var-file=variables.tfvars -auto-approve
