name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          token_format: 'access_token'
          audience: '//iam.googleapis.com/projects/hackathon-cp-project-team-1/locations/global/workloadIdentityPools/github-pool-demo/providers/github-provider-demo'
          workload_identity_provider: 'projects/hackathon-cp-project-team-1/locations/global/workloadIdentityPools/github-pool-demo/providers/github-provider-demo'
          service_account: hackathon-cp-project-team-1@appspot.gserviceaccount.com
          project_id: hackathon-cp-project-team-1
      - name: 'Access secret'
        run: |-
          curl https://secretmanager.googleapis.com/v1/projects/my-project/secrets/my-secret/versions/1:access \
            --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Apply
        run: terraform apply -auto-approve

