name: Deploy Infrastructure

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/1054015443281/locations/global/workloadIdentityPools/gemini-rag/providers/gemini-rag-provider'
          service_account: 'hackathon-cp-project-team-1@appspot.gserviceaccount.com'
          create_credentials_file: true
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'
          id_token_include_email: false


      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Set GCP project
        run: gcloud config set project hackathon-cp-project-team-1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
