name: 'Terraform Apply'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: hackathon-cp-project-team-1

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/1054015443281/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: my-github-actions-sa@hackathon-cp-project-team-1.iam.gserviceaccount.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Apply 
      id: apply
      run: |
          terraform apply -auto-approve
          deployment_ip_address=$(terraform output -raw deployment_ip_address | awk '{$1=$1};1' | awk 'NF' | sed 's/ *= */=/')
          last_line=$(echo "$deployment_ip_address" | tail -n 6 | head -n 1 | sed 's/::debug::stdout: //')
          echo "${last_line}" 
          deployment_ip_address=$last_line
          echo "deployment_ip_address=${deployment_ip_address}" >> $GITHUB_ENV
      env:
        GOOGLE_CLOUD_PROJECT: hackathon-cp-project-team-1

    - name: Update catalog-info.yaml
      run: |
        deployment_ip_address="${{ env.deployment_ip_address }}"
        sed -i '/links:/a \ \ \ \ - url: '"$deployment_ip_address"'\n \ \ \ \ \ title: Chatbot Link\n \ \ \ \ \ icon: chat' catalog-info.yaml


    - name: echo deployment_ip_address
      run: echo ${deployment_ip_address}  

    - name: Commit and Push Changes
      run: |
        git config --global user.email "wojciech.przybylski@ext.ons.gov.uk"
        git config --global user.name "WojciechP-ONS"
        git add catalog-info.yaml
        git commit -m "Add deployment IP address to catalog-info.yaml"
        git push