name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          workload_identity_provider: 'projects/1054015443281/locations/global/workloadIdentityPools/gemini-rag/providers/gemini-rag-provider'
          service_account: 'genai-rag-run-sa-0192aec6@hackathon-cp-project-team-1.iam.gserviceaccount.com'
          create_credentials_file: true
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'
          id_token_include_email: false
          project_id: 'hackathon-cp-project-team-1'


      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          workload_identity_provider: projects/hackathon-cp-project-team-1/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: hackathon-cp-project-team-1@appspot.gserviceaccount.com

      - name: Initialize Terraform
        run: terraform init
        
      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
